# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-25 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploy',
            name='address',
            field=models.CharField(blank=True, max_length=100, verbose_name='项目地址'),
        ),
    ]
